project_name: "ska_RL"
wandb: 'offline'
settings: wandb.Settings(_disable_stats=True)
num_agents: 2
episodes: 5
episode_length: 6
target_sensitivity: 100
target_resolution: 0.008
agent_type: DQN # Random, SGD, LOLA, PPO, DDPG, DQN
learning_rate: 0.001
batch_size: 2