project_name: "ska_RL_results"
wandb: 'online'
settings: wandb.Settings(_disable_stats=True)
num_agents: 2
episodes: 10
episode_length: 100
target_sensitivity: 100
target_resolution: 0.008
agent_type: Random # Random, SGD, LOLA, PPO, DDPG, DQN
learning_rate: 0.001
batch_size: 2